# Deep Neutral network model

In [11]:
import pandas as pd
import numpy as np
from math import sqrt
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from np_implementations.deep_nn import DNN
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

In [2]:
df = pd.read_csv('./mnist/train.csv')

In [3]:
binary_df = df.loc[df['label'].isin([0,1])]

In [4]:
binary_df['label']

0        1
1        0
2        1
4        0
5        0
        ..
41986    0
41988    0
41991    1
41995    0
41996    1
Name: label, Length: 8816, dtype: int64

In [5]:
X = binary_df.drop('label', axis=1).values
y = binary_df['label'].values

In [6]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
print('Shape of X: ', X.shape)
print('Shape of y: ', y.shape)

Shape of X:  (8816, 784)
Shape of y:  (8816,)


In [8]:
# load pickle file model.pkl
f = open('model.pkl', 'rb')
model = pickle.load(f)

In [9]:
y_pred = model.predict(X_test/255)
# confusion_matrix(y_test, y_pred, labels=[0, 1])

array([[816,   5],
       [  1, 942]])

In [12]:
roc_curve(y_test,y_pred)

(array([0.        , 0.00609013, 1.        ]),
 array([0.        , 0.99893955, 1.        ]),
 array([2, 1, 0]))

In [10]:
y_pred

array([1, 1, 1, ..., 1, 0, 1])